name: 给课表做个增强
description: 点击此项使增强课表
title: '[功能++?]: '
labels: [ "功能++?" ]
assignees: [ "daizihan233" ]

body:
  - type: markdown
    attributes:
      value: |
        ## 感谢您愿意花一些时间来填写这个内容！
        ## 以下是一些注意事项，能让提交更快被处理

        ### ❗ | 确定没有相同提议的 ISSUE 已被提出。
        ### ❔ | 提议时，如果文字无法说明清楚，不妨使用画图的方法辅助说明
        ### ⚠ | 如果涉及敏感信息，请自行打码

        ## 如果您不知道如何有效、精准地表述，建议您先阅读《提问的智慧》
        链接: [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
        ---
  - type: checkboxes
    id: terms
    attributes:
      label: |
        请确保您已阅读以上注意事项，并勾选下方的确认框。
      options:
        - label: "我已经仔细阅读上述教程和 [\"《提问的智慧》\"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。"
          required: true
        - label: "我确定这不是一个伪需求，他能解决实际存在的问题。"
          required: true
        - label: "我确定这是一个有意义的 Issue，且目前没有其他更好的解决方案。"
          required: true
        - label: "我确定在最近的 commit 提交所对应的版本中没有这个功能"
          required: true
        - label: "我愿意为此功能提交 Pull Request，或者提供一些实现思路（非必选）"
          required: false
  - type: checkboxes
    id: captcha
    attributes:
      label: |
        为了确保你是人类，请阅读并勾选以下内容，如有错选本仓库所有者可能会直接关闭此 Issue。Just kidding!
      options:
        - label: "我保证我已经认真阅读了以上说明，并已经勾选上面的选项"  # y
        - label: "我不确定我有认真阅读了以上说明，并没有勾选了上面的选项"  # x
        - label: "我确定我没有已经认真阅读了以上说明，并已经勾选上面的选项"  # x
        - label: "我不否认我确认了我已经认真阅读了以上说明，并否认我确定没有勾选上面的选项"  # y
        - label: "我确定我没有认真阅读了以上说明，并没有勾选上面的选项"  # x
        - label: "我不确定我没有认真阅读了以上说明，并勾选了上面的选项"  # y
        - label: "我承诺我以上所勾选的信息是不属实的"  # x
        - label: "我承诺我以上所勾选的信息不是错误的"  # y

  - type: markdown
    attributes:
      value: |
        ## 相关信息
        请根据实际使用环境修改以下信息。

  - type: input
    id: name
    attributes:
      label: 功能名称
      description: 你要对哪个功能进行增强？
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 简述这个增强功能是干嘛的
    validations:
      required: true

  - type: textarea
    id: mean
    attributes:
      label: 新功能意义
      description: 简述这个增强功能的意义在哪
    validations:
      required: true

  - type: dropdown
    id: part-type
    attributes:
      label: 您反馈的建议属于以下哪个部分？
      description: 如果您确实不知道属于什么，可以选择 “我不确定”；如果需要多个部分同时修改，应该选择 “复合”
      options:
        - 客户端（AstraSchedule）
        - 管理端（AstraScheduleWeb）
        - 服务端（新版，AstraScheduleServerGo）
        - 服务端（旧版，AstraScheduleServer，可能废弃！）
        - 复合
        - 我不确定
    validations:
      required: true

  - type: textarea
    id: how-to
    attributes:
      label: 实现方案（可选）
      description: 如果您有什么好的实现方案，那么可以写在这里

  - type: textarea
    id: extra-desc
    attributes:
      label: 补充说明（可选）
